
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui/

server:
  port: ${PORT:0}

config:
  endpoint:
    enterprise-customers: lb://customer-service/api/enterprise-customers

path:
  accounts: /api/accounts